<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_668c98c21333f',
	'title' => 'About us 이미지',
	'fields' => array(
		array(
			'key' => 'field_66986ae1c69ed',
			'label' => '',
			'name' => 'about_us',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_6699b8f56ce31',
					'label' => '비주얼',
					'name' => 'visual',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '* 등록된 이미지가 없을 경우 사용자 화면에서 표시되지 않습니다.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 10,
					'collapsed' => '',
					'button_label' => '추가',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6699b8f56ce32',
							'label' => '이미지',
							'name' => 'image',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_6699b8f56ce33',
									'label' => 'PC 이미지',
									'name' => 'pc',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 1903 x 953 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'preview_size' => 'medium',
								),
								array(
									'key' => 'field_669f4e168dac8',
									'label' => '모바일 이미지',
									'name' => 'mobile',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적사이즈 780 x 1688 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'allow_in_bindings' => 1,
									'preview_size' => 'medium',
								),
							),
							'parent_repeater' => 'field_6699b8f56ce31',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'jt-about-image-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_668cd0fb0d8c7',
	'title' => 'ARTINUS',
	'fields' => array(
		array(
			'key' => 'field_668cd0fb25201',
			'label' => '',
			'name' => 'artinus',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_668cd12325202',
					'label' => '영문명칭',
					'name' => 'en_name',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 2,
					'placeholder' => '국문 명칭을 입력해 주세요.',
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_668cd14725203',
					'label' => '국문명칭',
					'name' => 'ko_name',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 2,
					'placeholder' => '국문 명칭을 입력해 주세요.',
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_668cd49c25204',
					'label' => '디스크립션',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => 200,
					'rows' => 8,
					'placeholder' => '디스크립션을 입력해 주세요. (공백 포함 200자)',
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_668cdd9a25205',
					'label' => '썸네일 등록',
					'name' => 'thumbnail',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_668cde5125206',
							'label' => '리스트 이미지(big)',
							'name' => 'big',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '* 최적 사이즈 892 x 692 px, 2MB 이하 png 파일형식으로 등록 가능합니다.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => 2,
							'mime_types' => '.png',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_668cde8825208',
							'label' => '리스트 이미지(small)',
							'name' => 'small',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '* 최적 사이즈 320 x 240 px, 2MB 이하 png 파일형식으로 등록 가능합니다.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => 2,
							'mime_types' => '.png',
							'preview_size' => 'medium',
						),
					),
				),
				array(
					'key' => 'field_668ce13338566',
					'label' => '본문 이미지 / 영상',
					'name' => 'visual',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_668ce23f38567',
							'label' => '이미지',
							'name' => 'image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '* 최적 사이즈 875 x 492 px, 2MB 이하	jpg, png 파일형식으로 등록 가능합니다.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => 2,
							'mime_types' => '.png, .jpg',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_668ce2c238568',
							'label' => '',
							'name' => 'video_use',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '* ON 활성화시 사용자 화면에 노출되고 OFF 비활성화시 노출되지 않습니다.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => 'ON',
							'ui_off_text' => 'OFF',
							'ui' => 1,
						),
						array(
							'key' => 'field_668ce34038569',
							'label' => '영상',
							'name' => 'video',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '* 비메오 URL https://vimeo.com/영상번호 예) 123456789',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_668ce2c238568',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => 'vimeo 임베드 주소를 입력해주세요.',
							'prepend' => '',
							'append' => '',
						),
					),
				),
				array(
					'key' => 'field_668ce79d2c7c5',
					'label' => '정보',
					'name' => 'info',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 1,
					'max' => 0,
					'collapsed' => '',
					'button_label' => '추가',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_668ce7e12c7c6',
							'label' => '항목',
							'name' => 'item',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => 20,
							'placeholder' => '항목을 입력해 주세요. (공백포함, 20자 이내)',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_668ce79d2c7c5',
						),
						array(
							'key' => 'field_668ce7fc2c7c7',
							'label' => '내용',
							'name' => 'content',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => 50,
							'placeholder' => '내용을 입력해 주세요. (공백포함, 50자 이내)',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_668ce79d2c7c5',
						),
					),
				),
				array(
					'key' => 'field_668ce960f4240',
					'label' => '특징',
					'name' => 'characteristic',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 8,
					'placeholder' => '',
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_668cea63e88ee',
					'label' => '버튼 링크',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '* 미 입력시 노출되지 않으며, 최대 5개까지 등록 가능합니다.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 5,
					'collapsed' => '',
					'button_label' => '추가',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_668ceabfe88ef',
							'label' => '버튼명',
							'name' => 'name',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => 30,
							'placeholder' => '버튼명을 입력해 주세요. (공백포함 최대 30글자)',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_668cea63e88ee',
						),
						array(
							'key' => 'field_668ceb17e88f0',
							'label' => 'URL',
							'name' => 'url',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'URL 주소를 입력해 주세요.',
							'parent_repeater' => 'field_668cea63e88ee',
						),
						array(
							'key' => 'field_668ceb6ce88f1',
							'label' => '새창 열기',
							'name' => 'target',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => 'ON',
							'ui_off_text' => 'OFF',
							'ui' => 1,
							'parent_repeater' => 'field_668cea63e88ee',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'artinus',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_668e39fe5602e',
	'title' => 'COFFEE BEANS',
	'fields' => array(
		array(
			'key' => 'field_668e39fe5e316',
			'label' => '',
			'name' => 'coffee_beans',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_668e3a735e317',
					'label' => '썸네일 등록',
					'name' => 'thumbnail',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_66a72f6929a72',
							'label' => '리스트 이미지(big)',
							'name' => 'big',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '* 최적 사이즈 892 x 692 px, 2MB 이하 png 파일형식으로 등록 가능합니다.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => 2,
							'mime_types' => '.png',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_66a72f7f29a73',
							'label' => '리스트 이미지(small)',
							'name' => 'small',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '* 최적 사이즈 320 x 240 px, 2MB 이하 png 파일형식으로 등록 가능합니다.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => 2,
							'mime_types' => '.png',
							'preview_size' => 'medium',
						),
					),
				),
				array(
					'key' => 'field_668f79164329a',
					'label' => '제품 명칭',
					'name' => 'product_name',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => 20,
					'rows' => 2,
					'placeholder' => '리스트에 나타낼 제품 명칭을 입력해 주세요. (공백 포함 20글자)',
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_668f77c59d32a',
					'label' => '상세 정보 노출',
					'name' => 'use',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui_on_text' => 'ON',
					'ui_off_text' => 'OFF',
					'ui' => 1,
				),
				array(
					'key' => 'field_668f78549d32b',
					'label' => '',
					'name' => 'data',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_668f77c59d32a',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_668e3af85e318',
							'label' => '상세정보',
							'name' => 'info',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_668e3bff5e31b',
									'label' => '서브 타이틀',
									'name' => 'sub_title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 50,
									'placeholder' => '원두 서브 타이틀을 입력해 주세요. (공백 포함 50글자)',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_668e3b225e319',
									'label' => '본문 이미지',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 1171 x 954 px, 2MB 이하 png 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.png',
									'preview_size' => 'medium',
								),
								array(
									'key' => 'field_668e3c315e31c',
									'label' => '디스크립션',
									'name' => 'description',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 200,
									'rows' => 8,
									'placeholder' => '디스크립션을 입력해 주세요. (공백 포함 200자)',
									'new_lines' => 'br',
								),
							),
						),
						array(
							'key' => 'field_668e3c8a5e31d',
							'label' => '커핑노트',
							'name' => 'cupping_note',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_668e3d2f5e31e',
									'label' => '대표 노트',
									'name' => 'representative_note',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 100,
									'placeholder' => '대표 노트를 입력해 주세요. (공백 포함 100자)',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_668e3d895e31f',
									'label' => '노트 수치 입력',
									'name' => 'figure',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '* 미 입력시 히든처리',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'row',
									'sub_fields' => array(
										array(
											'key' => 'field_668e3e035e320',
											'label' => '초콜릿',
											'name' => 'chocolate',
											'aria-label' => '',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'min' => 0,
											'max' => 100,
											'placeholder' => '숫자만 기입 (0~100)',
											'step' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_668e3e725e321',
											'label' => '견과류',
											'name' => 'nuts',
											'aria-label' => '',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'min' => 0,
											'max' => 100,
											'placeholder' => '숫자만 기입 (0~100)',
											'step' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_668e3e775e322',
											'label' => '카라멜',
											'name' => 'caramel',
											'aria-label' => '',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'min' => 0,
											'max' => 100,
											'placeholder' => '숫자만 기입 (0~100)',
											'step' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_668e3e795e323',
											'label' => '바디',
											'name' => 'body',
											'aria-label' => '',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'min' => 0,
											'max' => 100,
											'placeholder' => '숫자만 기입 (0~100)',
											'step' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_668e3e7d5e324',
											'label' => '꽃향기',
											'name' => 'flowers',
											'aria-label' => '',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'min' => 0,
											'max' => 100,
											'placeholder' => '숫자만 기입 (0~100)',
											'step' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_668e3e815e325',
											'label' => '베리류 과일',
											'name' => 'berryfruit',
											'aria-label' => '',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'min' => 0,
											'max' => 100,
											'placeholder' => '숫자만 기입 (0~100)',
											'step' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_668e3e845e326',
											'label' => '감귤류 과일',
											'name' => 'citrusfruit',
											'aria-label' => '',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'min' => 0,
											'max' => 100,
											'placeholder' => '숫자만 기입 (0~100)',
											'step' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_668e3e885e327',
											'label' => '달콤한 과일',
											'name' => 'sweetfruit',
											'aria-label' => '',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'min' => 0,
											'max' => 100,
											'placeholder' => '숫자만 기입 (0~100)',
											'step' => '',
											'prepend' => '',
											'append' => '',
										),
									),
								),
							),
						),
						array(
							'key' => 'field_668e3f9e5e328',
							'label' => '제품 정보',
							'name' => 'product_info',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'pagination' => 0,
							'min' => 0,
							'max' => 6,
							'collapsed' => '',
							'button_label' => '추가',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_668e40145e32a',
									'label' => '항목',
									'name' => 'item',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 20,
									'placeholder' => '항목을 입력해 주세요. (공백포함, 20자 이내)',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_668e3f9e5e328',
								),
								array(
									'key' => 'field_668e408a5e32b',
									'label' => '내용',
									'name' => 'content',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 150,
									'placeholder' => '내용을 입력해 주세요. (공백포함, 150자 이내)',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_668e3f9e5e328',
								),
							),
						),
						array(
							'key' => 'field_668e413e5e32c',
							'label' => '버튼 링크',
							'name' => 'link',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '* 미 입력시 노출되지 않으며, 최대 5개까지 등록 가능합니다.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'pagination' => 0,
							'min' => 0,
							'max' => 3,
							'collapsed' => '',
							'button_label' => '추가',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_668e41915e32d',
									'label' => '버튼명',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 30,
									'placeholder' => '버튼명을 입력해 주세요. (공백포함 최대 30글자)',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_668e413e5e32c',
								),
								array(
									'key' => 'field_668e419c5e32e',
									'label' => 'URL',
									'name' => 'url',
									'aria-label' => '',
									'type' => 'url',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'URL 주소를 입력해 주세요.',
									'parent_repeater' => 'field_668e413e5e32c',
								),
								array(
									'key' => 'field_668e42115e32f',
									'label' => '새창 열기',
									'name' => 'target',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui_on_text' => 'ON',
									'ui_off_text' => 'OFF',
									'ui' => 1,
									'parent_repeater' => 'field_668e413e5e32c',
								),
							),
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'coffee_beans',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_668c8849ca776',
	'title' => 'FAQs',
	'fields' => array(
		array(
			'key' => 'field_668c8849cc19f',
			'label' => '',
			'name' => 'faqs',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_668c8849ccda9',
					'label' => '답변',
					'name' => 'answer',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 8,
					'placeholder' => '',
					'new_lines' => 'br',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'faqs',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66d7b907227ee',
	'title' => '공통 관리',
	'fields' => array(
		array(
			'key' => 'field_66d7b908934bc',
			'label' => '',
			'name' => 'common_settings',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_66d7b92a934bd',
					'label' => '무역',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_66d7c3e9635d1',
					'label' => '',
					'name' => 'trade',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66d7c411635d2',
							'label' => '내용 입력',
							'name' => 'content',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'pagination' => 0,
							'min' => 4,
							'max' => 4,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_66d7c473635d3',
									'label' => '타이틀',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 15,
									'allow_in_bindings' => 1,
									'placeholder' => '최대 15글자 입력해 주세요. (영문권장, 공백제외)',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_66d7c411635d2',
								),
								array(
									'key' => 'field_66d7c489635d4',
									'label' => '내용',
									'name' => 'description',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 90,
									'allow_in_bindings' => 1,
									'rows' => 8,
									'placeholder' => '최대 90 글자 입력 권장 (공백제외)',
									'new_lines' => 'br',
									'parent_repeater' => 'field_66d7c411635d2',
								),
								array(
									'key' => 'field_66d7c4a5635d5',
									'label' => '이미지',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_66d7c4bb635d6',
											'label' => 'PC 이미지',
											'name' => 'pc',
											'aria-label' => '',
											'type' => 'image',
											'instructions' => '* 최적 사이즈 398 x 300px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => 2,
											'mime_types' => '.jpg, .png, .webp',
											'allow_in_bindings' => 1,
											'preview_size' => 'medium',
										),
									),
									'parent_repeater' => 'field_66d7c411635d2',
								),
							),
						),
						array(
							'key' => 'field_66d7c4f9635d7',
							'label' => '하단 이미지',
							'name' => 'bottom_image',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_66d7c519635d8',
									'label' => 'PC 이미지',
									'name' => 'pc',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 1903 x 954 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'allow_in_bindings' => 1,
									'preview_size' => 'medium',
								),
								array(
									'key' => 'field_66d7c520635d9',
									'label' => '모바일 이미지',
									'name' => 'mobile',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 780 x 1000 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'allow_in_bindings' => 1,
									'preview_size' => 'medium',
								),
							),
						),
					),
				),
				array(
					'key' => 'field_66d7b96d934be',
					'label' => '제조',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_66d7d58635751',
					'label' => '',
					'name' => 'making',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66d7d5e535752',
							'label' => '내용 입력',
							'name' => 'content',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'pagination' => 0,
							'min' => 6,
							'max' => 6,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_66d7d66535753',
									'label' => '타이틀',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 15,
									'allow_in_bindings' => 1,
									'placeholder' => '최대 15글자 입력해 주세요. (영문권장, 공백제외)',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_66d7d5e535752',
								),
								array(
									'key' => 'field_66d7d6b035754',
									'label' => '내용',
									'name' => 'description',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 20,
									'allow_in_bindings' => 1,
									'rows' => 8,
									'placeholder' => '최대 20 글자 입력 권장 (공백제외)',
									'new_lines' => 'br',
									'parent_repeater' => 'field_66d7d5e535752',
								),
								array(
									'key' => 'field_66d7d6c435755',
									'label' => '이미지',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_66d7d6d035756',
											'label' => 'PC 이미지',
											'name' => 'pc',
											'aria-label' => '',
											'type' => 'image',
											'instructions' => '* 최적 사이즈 449x350 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => 2,
											'mime_types' => '.jpg, .png, .webp',
											'allow_in_bindings' => 1,
											'preview_size' => 'medium',
										),
									),
									'parent_repeater' => 'field_66d7d5e535752',
								),
							),
						),
					),
				),
				array(
					'key' => 'field_66d7b976934bf',
					'label' => '컨설팅',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_66d7daf5bedb9',
					'label' => '',
					'name' => 'consulting',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66d7daf5bedba',
							'label' => '내용 입력',
							'name' => 'content',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'pagination' => 0,
							'min' => 6,
							'max' => 6,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_66d7daf5bedbb',
									'label' => '타이틀',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 20,
									'allow_in_bindings' => 1,
									'placeholder' => '최대 20글자 입력해 주세요. (영문권장, 공백제외)',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_66d7daf5bedba',
								),
								array(
									'key' => 'field_66d7daf5bedbc',
									'label' => '내용',
									'name' => 'description',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 50,
									'allow_in_bindings' => 1,
									'rows' => 8,
									'placeholder' => '최대 50 글자 입력 권장 (공백제외)',
									'new_lines' => 'br',
									'parent_repeater' => 'field_66d7daf5bedba',
								),
								array(
									'key' => 'field_66d7daf5bedbd',
									'label' => '이미지',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'group',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_66d7daf5bedbe',
											'label' => 'PC 이미지',
											'name' => 'pc',
											'aria-label' => '',
											'type' => 'image',
											'instructions' => '* 최적 사이즈 1903 x 953 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => 2,
											'mime_types' => '.jpg, .png, .webp',
											'allow_in_bindings' => 1,
											'preview_size' => 'medium',
										),
									),
									'parent_repeater' => 'field_66d7daf5bedba',
								),
							),
						),
						array(
							'key' => 'field_66d7daf5bedbf',
							'label' => '하단 이미지',
							'name' => 'bottom_image',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_66d7daf5bedc0',
									'label' => 'PC 이미지',
									'name' => 'pc',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 1903 x 954 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'allow_in_bindings' => 1,
									'preview_size' => 'medium',
								),
								array(
									'key' => 'field_66d7daf5bedc1',
									'label' => '모바일 이미지',
									'name' => 'mobile',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 780 x 1000 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'allow_in_bindings' => 1,
									'preview_size' => 'medium',
								),
							),
						),
					),
				),
				array(
					'key' => 'field_66d7b983934c0',
					'label' => '브랜드',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_66d7d74735757',
					'label' => '',
					'name' => 'brand',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66d7d7b035758',
							'label' => 'JMCOFFEE 이미지 관리',
							'name' => 'jmcoffee_image',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'pagination' => 0,
							'min' => 1,
							'max' => 10,
							'collapsed' => '',
							'button_label' => '추가',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_66d7d8f53575a',
									'label' => 'PC 이미지',
									'name' => 'pc',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 1816 x 866 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'allow_in_bindings' => 1,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_66d7d7b035758',
								),
								array(
									'key' => 'field_66d7d90f3575b',
									'label' => '모바일 이미지',
									'name' => 'mobile',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 780x1000 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'allow_in_bindings' => 1,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_66d7d7b035758',
								),
							),
						),
						array(
							'key' => 'field_66d7d7bf35759',
							'label' => 'COMPOSE 이미지 관리',
							'name' => 'compose_image',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'pagination' => 0,
							'min' => 1,
							'max' => 10,
							'collapsed' => '',
							'button_label' => '추가',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_66d7d9553575c',
									'label' => 'PC 이미지',
									'name' => 'pc',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 1816 x 866 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'allow_in_bindings' => 1,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_66d7d7bf35759',
								),
								array(
									'key' => 'field_66d7d9573575d',
									'label' => '모바일 이미지',
									'name' => 'mobile',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '* 최적 사이즈 780x1000 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => 2,
									'mime_types' => '.jpg, .png, .webp',
									'allow_in_bindings' => 1,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_66d7d7bf35759',
								),
							),
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'jt-common-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_668c8e00cbe0c',
	'title' => '뉴스',
	'fields' => array(
		array(
			'key' => 'field_668c8e031fefe',
			'label' => '',
			'name' => 'news',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_668c8e261feff',
					'label' => '카테고리',
					'name' => 'category',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'news_categories',
					'add_term' => 0,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'object',
					'field_type' => 'radio',
					'allow_null' => 0,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_668c904cc2149',
					'label' => '특성 이미지',
					'name' => 'thumbnail',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '* 최적 사이즈 443 x 443 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => 2,
					'mime_types' => '.jpg, .png, .webp',
					'preview_size' => 'medium',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'news',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66d6b229d71b2',
	'title' => '매장안내',
	'fields' => array(
		array(
			'key' => 'field_66d6b22a52afc',
			'label' => '',
			'name' => 'store',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_66d6b25386fdd',
					'label' => '정보입력',
					'name' => 'info',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_66d6b8d2debac',
							'label' => '영업시간',
							'name' => 'time',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 1,
							'placeholder' => '영업시간을 입력해 주세요.',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_66d6b8ebdebad',
							'label' => '주소',
							'name' => 'address',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 1,
							'placeholder' => '주소를 입력해 주세요.',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_66d6b906debae',
							'label' => '전화번호',
							'name' => 'tel',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 1,
							'placeholder' => '전화번호를 입력해 주세요.',
							'prepend' => '',
							'append' => '',
						),
					),
				),
				array(
					'key' => 'field_66d6b27586fde',
					'label' => '맵 정보',
					'name' => 'map',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_66d6b79865d4e',
							'label' => '카카오맵',
							'name' => 'kakao',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 1,
							'placeholder' => 'URL 주소를 입력해 주세요.',
						),
						array(
							'key' => 'field_66d6b7d865d4f',
							'label' => '네이버맵',
							'name' => 'naver',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 1,
							'placeholder' => 'URL 주소를 입력해 주세요.',
						),
						array(
							'key' => 'field_66d6b7e265d50',
							'label' => '구글맵',
							'name' => 'google',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 1,
							'placeholder' => 'URL 주소를 입력해 주세요.',
						),
					),
				),
				array(
					'key' => 'field_66d6b2e686fdf',
					'label' => '스토어 이미지',
					'name' => 'image',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '* 첫번째 이미지가 대표 썸네일 이미지로 노출됩니다. (최대 10장)',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'pagination' => 0,
					'min' => 1,
					'max' => 10,
					'collapsed' => '',
					'button_label' => '추가',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_66d6b3e910274',
							'label' => '',
							'name' => 'pc',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '* 최적 사이즈 892 x 594 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => 2,
							'mime_types' => '.jpg, .png, .webp',
							'allow_in_bindings' => 1,
							'preview_size' => 'medium',
							'parent_repeater' => 'field_66d6b2e686fdf',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'store',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66863ec6d765b',
	'title' => '문의유형 관리',
	'fields' => array(
		array(
			'key' => 'field_66863ec7a18b8',
			'label' => '',
			'name' => 'inquiry_type',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '문의유형 담당자 지정
입력하지 않을 경우, 담당자 메일 발송이 작동하지 않습니다.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 1,
			'max' => 0,
			'collapsed' => 'field_66863fbda18b9',
			'button_label' => '추가',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_66863fbda18b9',
					'label' => '항목',
					'name' => 'type',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_66863ec7a18b8',
				),
				array(
					'key' => 'field_668648e13c955',
					'label' => '',
					'name' => 'send',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'min' => 1,
					'max' => 0,
					'collapsed' => '',
					'button_label' => '추가',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_668648f73c956',
							'label' => '담당자 이메일',
							'name' => 'email',
							'aria-label' => '',
							'type' => 'email',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_668648e13c955',
						),
					),
					'parent_repeater' => 'field_66863ec7a18b8',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'jt-inquiry-type-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66d6aefc2b10a',
	'title' => '설치사례',
	'fields' => array(
		array(
			'key' => 'field_66d6aefc6ab32',
			'label' => '',
			'name' => 'portfolio',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_66d6af2c6ab33',
					'label' => '특성 이미지',
					'name' => 'thumbnail',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '* 최적 사이즈 443 x 443 px, 2MB 이하 jpg, png, webp 파일형식으로 등록 가능합니다.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => 2,
					'mime_types' => '.jpg, .png, .webp',
					'allow_in_bindings' => 1,
					'preview_size' => 'medium',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_668ca02181a43',
	'title' => '연혁',
	'fields' => array(
		array(
			'key' => 'field_668ca02136ba1',
			'label' => '',
			'name' => 'history',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_668ca04c36ba2',
					'label' => '',
					'name' => 'year_data',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'pagination' => 0,
					'min' => 1,
					'max' => 0,
					'collapsed' => 'field_668cb3b1ad520',
					'button_label' => '추가',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_668cb3b1ad520',
							'label' => '연도(앞 2자리)',
							'name' => 'front_number',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_668ca04c36ba2',
						),
						array(
							'key' => 'field_668cb3e0ad521',
							'label' => '',
							'name' => 'data',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'min' => 1,
							'max' => 0,
							'collapsed' => 'field_668cb53dad524',
							'button_label' => '추가',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_668cb53dad524',
									'label' => '연도(뒤 2자리)',
									'name' => 'back_number',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_668cb3e0ad521',
								),
								array(
									'key' => 'field_668cb409ad522',
									'label' => '주요 내용',
									'name' => 'main_contents',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'rows' => 8,
									'placeholder' => '',
									'new_lines' => 'br',
									'parent_repeater' => 'field_668cb3e0ad521',
								),
								array(
									'key' => 'field_668cb4a9ad523',
									'label' => '내용',
									'name' => 'contents',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'rows' => 8,
									'placeholder' => '',
									'new_lines' => 'br',
									'parent_repeater' => 'field_668cb3e0ad521',
								),
							),
							'parent_repeater' => 'field_668ca04c36ba2',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'jt-history-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

add_action( 'acf/init', function() {
	acf_add_options_page( array(
	'page_title' => 'About us 이미지',
	'menu_slug' => 'jt-about-image-settings',
	'position' => '',
	'redirect' => true,
	'menu_icon' => array(
		'type' => 'dashicons',
		'value' => 'dashicons-format-gallery',
	),
	'icon_url' => 'dashicons-format-gallery',
) );

	acf_add_options_page( array(
	'page_title' => 'Business',
	'menu_slug' => 'jt-page-settings',
	'position' => '',
	'redirect' => true,
	'menu_icon' => array(
		'type' => 'dashicons',
		'value' => 'dashicons-businessperson',
	),
	'icon_url' => 'dashicons-businessperson',
) );

	acf_add_options_page( array(
	'page_title' => '공통 관리',
	'menu_slug' => 'jt-common-settings',
	'parent_slug' => 'jt-page-settings',
	'position' => '',
	'redirect' => false,
) );

	acf_add_options_page( array(
	'page_title' => '문의유형 관리',
	'menu_slug' => 'jt-inquiry-type-settings',
	'parent_slug' => 'jt-inquiry',
	'position' => '',
	'redirect' => false,
	'update_button' => '변경사항 저장',
) );

	acf_add_options_page( array(
	'page_title' => '연혁',
	'menu_slug' => 'jt-history-settings',
	'position' => '',
	'redirect' => true,
	'menu_icon' => array(
		'type' => 'dashicons',
		'value' => 'dashicons-backup',
	),
	'icon_url' => 'dashicons-backup',
) );
} );

